version: '3.3'

services:
  web:
    image: nginx:latest
    ports:
      - '8081:80'
    volumes:
      - .:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm
  php-fpm:
    image: conference-registration
    volumes:
      - .:/var/www/html
